config/routes.rb
Rails.application.routes.draw do
  resources :service_attachments

  resources :enquiries

  resources :services

  resources :static_pages

  resources :enquiries, path: "contact" do 
    collection do 
      get "thanks"
    end
  end

  root 'static_pages#index'

  match "/about-us", to: "static_pages#about", via: "get"

  match "/contact", to: "enquiries#index", via: "get"

end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  mount_uploader :image, PictureUploader
  belongs_to :service
end

app/models/service.rb
class Service < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    new_record?
  end

  has_many :sub_services, foreign_key: 'service_id', class_name: 'Service'
  belongs_to :parent, foreign_key: 'service_id', class_name: 'Service'
  has_many :service_attachments
  accepts_nested_attributes_for :service_attachments
  has_many :galleries
  accepts_nested_attributes_for :galleries

end

app/models/service_attachment.rb
class ServiceAttachment < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :service
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  # GET /enquiries
  def index
    @enquiry = Enquiry.new
  end

  # POST /enquiries
  def create
    @enquiry = Enquiry.new(enquiry_params)

    if @enquiry.save
      redirect_to thanks_enquiries_path, notice: 'Enquiry was successfully created.'
    else
      render :new
    end
  end
  private
    # Only allow a trusted parameter "white list" through.
    def enquiry_params
      params.require(:enquiry).permit(:name, :email, :body)
    end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.save
      redirect_to @gallery, notice: 'Gallery was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /galleries/1
  def update
    if @gallery.update(gallery_params)
      redirect_to @gallery, notice: 'Gallery was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /galleries/1
  def destroy
    @gallery.destroy
    redirect_to galleries_url, notice: 'Gallery was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def gallery_params
      params[:gallery]
    end
end

app/controllers/service_attachments_controller.rb
class ServiceAttachmentsController < ApplicationController
  before_action :set_service_attachment, only: [:show, :edit, :update, :destroy]

  # GET /service_attachments
  def index
    @service_attachments = ServiceAttachment.all
  end

  # GET /service_attachments/1
  def show    
  end

  # GET /service_attachments/new
  def new
    @service_attachment = ServiceAttachment.new
  end

  # GET /service_attachments/1/edit
  def edit
  end

  # POST /service_attachments
  def create
    @service_attachment = ServiceAttachment.new(service_attachment_params)

    if @service_attachment.save
      redirect_to @service_attachment, notice: 'Service attachment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /service_attachments/1
  def update
    respond_to do |format|
      if @service_attachment.update(service_attachment_params)
        format.html { redirect_to @service_attachment.service, notice: 'Service attachment was successfully updated.' }
      end 
    end
  end

  # DELETE /service_attachments/1
  def destroy
    @service_attachment.destroy
    redirect_to service_attachments_url, notice: 'Service attachment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_attachment
      @service_attachment = ServiceAttachment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def service_attachment_params
      params.require(:service_attachment).permit(:service_id, :picture)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    redirect_to about_us_path
    @services = Service.all
  end

  def Art
    @services = @art_services
    render 'index' 
  end
  
  def Furniture
    @services = @furniture_services
    render 'index'
  end

  def show
    @service = Service.friendly.find(params[:id])
    @services = Service.all
    @service_attachments = @service.service_attachments
    @galleries = @service.galleries
  end

  def new
    @service = Service.new
    @service_attachment = @service.service_attachments.build
    @galleries = @service.galleries.build
  end

  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        if params[:service_attachments]
          params[:service_attachments]['picture'].each do |a|
            @service_attachment = @service.service_attachments.create!(:picture => a, :service_id => @service.id)
          end
        end
        if params[:galleries]
          params[:galleries]['image'].each do |a|
            @galleries = @service.galleries.create!(:image => a, :service_id => @service.id)
          end
        end
        format.html { redirect_to @service, notice: 'service was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  private

    def set_service
      @service = Service.find(params[:id])
    end
    
    def service_params
      params.require(:service).permit(:title, :service_id, :primary, :quote, :body, service_attachments_attributes: [:id, :service_id, :picture], galleries_attributes: [:id, :service_id, :image])
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @static_pages = StaticPage.all
    @services = Service.all
    @galleries = Gallery.all
    @service_attachments = ServiceAttachment.all
    @primary_services = Service.where(primary: nil)
  end

  def home
    @enquiry = Enquiry.new
    @primary_services = Service.where(primary: true)
  end

  def about
    @services = Service.all
    @art_services = Service.where(service_type: "art")
    @furniture_services = Service.where(service_type: "furniture")  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/service_attachments_helper.rb
module ServiceAttachmentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/enquiries/_form.html.haml
= form_for(@enquiry) do |f|
  - if @enquiry.errors.any?
    #error_explanation
      %h2
        = pluralize(@enquiry.errors.count, "error")
        prohibited this enquiry from being saved:
      %ul
        - @enquiry.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :body, 'How can we help?'
    %br/
    = f.text_area :body
  .actions_button
    = f.submit'Submit'

app/views/enquiries/edit.html.haml
<h1>Editing enquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/index.html.haml
.content
  .enquiries_text.column.split_3
    %p Contact us using the details below or the form.<br><br>
    %p Tel: 07733 36 35 34
    %p Email:
    %a{:href => "mailto:shop@woodenartworld.co.uk"} shop@woodenartworld.co.uk
    \/<br>
    %a{:href => "mailto:john.yarnton@hotmail.com"} john.yarnton@hotmail.com
    %p address:<br>3 Blake Road<br>Ipswich<br>Suffolk<br>IP1 6EN
  .enquiry_form.column.split_4
    = render 'enquiries/form'

app/views/enquiries/new.html.haml
<h1>New enquiry</h1>

<%= render 'form' %>

<%= link_to 'Back', enquiries_path %>

app/views/enquiries/show.html.haml
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enquiry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @enquiry.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @enquiry.body %>
</p>

<%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |
<%= link_to 'Back', enquiries_path %>

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<h1>Listing galleries</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= link_to 'Show', gallery %></td>
        <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
        <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

app/views/layouts/_footer.html.haml
.footer
  .footer_inner
    %ul.footer_left
      %li &copy; Copyright 2013 Wooden Art World LTD. #{link_to 'Disclaimer', root_path}
    %ul.footer_middle
      %li.footer_middle_left
        = link_to 'Contact Us', root_path
      %li.footer_middle_middle 
        = link_to 'About Us', root_path
      %li.footer_middle_right  
        = link_to 'Sitemap', root_path
    %ul.footer_right
      %li
        = link_to 'Web Design Norwich', 'http://www.cd2solutions.co.uk'

app/views/layouts/_header.html.haml
.top_strip.clearfix
  .top_strip_inner
    %ul.left_top_strip
      %li
        = link_to 'Facebook', 'https://www.facebook.com/pages/Wooden-Art-World/542876149081768'
      %li
        = link_to 'Twitter', 'https://twitter.com/WoodenArtWorld'
      %li
        = link_to 'Instagram', 'https://instagram.com/woodenartworld/'
      %li
        = link_to 'Pintrest', 'https://www.pinterest.com/woodenartworld/'
    %ul.right_top_strip
      %li <span class="t_and_e">T.</span> 01263 713570
      %li <span class="t_and_e">E.</span> Shop@woodenArtWorld.co.uk
.header_wrapper
  .logo
    =link_to image_tag('logo2.jpg'), root_path
  %ul.header_links
    - Service.where(primary: true).each do |service|
      %li= link_to service.title, service
    %li
      = link_to 'about', about_us_path
    %li
      = link_to 'contact', contact_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title WoodenArtWorld
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %script{:src => "//use.typekit.net/nyz6ggw.js"}
    :javascript
      try{Typekit.load();}catch(e){}
  %body
    .general_wrap
      = render 'layouts/header'
      = yield
      =render 'layouts/footer'

app/views/service_attachments/_form.html.erb
<%= form_for(@service_attachment) do |f| %>
  <% if @service_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_attachment.errors.count, "error") %> prohibited this service_attachment from being saved:</h2>

      <ul>
      <% @service_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :service_id %><br>
    <%= f.number_field :service_id %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_attachments/edit.html.erb
<h1>Editing service_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_attachment %> |
<%= link_to 'Back', service_attachments_path %>

app/views/service_attachments/index.html.erb
<h1>Listing service_attachments</h1>

<table>
  <thead>
    <tr>
      <th>Service</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_attachments.each do |service_attachment| %>
      <tr>
        <td><%= service_attachment.service_id %></td>
        <td><%= service_attachment.picture %></td>
        <td><%= link_to 'Show', service_attachment %></td>
        <td><%= link_to 'Edit', edit_service_attachment_path(service_attachment) %></td>
        <td><%= link_to 'Destroy', service_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service attachment', new_service_attachment_path %>

app/views/service_attachments/new.html.erb
<h1>New service_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', service_attachments_path %>

app/views/service_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service:</strong>
  <%= @service_attachment.service_id %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @service_attachment.picture %>
</p>

<%= link_to 'Edit', edit_service_attachment_path(@service_attachment) %> |
<%= link_to 'Back', service_attachments_path %>

app/views/services/_form.html.haml
= form_for(@service, :html => { :multipart => true }) do |f|
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :quote
    = f.text_field :quote
  = f.fields_for :service_attachments do |p|
    .field
      = p.label :picture, 'choose up to 9 head pictures'
      %br/
      = p.file_field :picture, :multiple => true, name: "service_attachments[picture][]"
  .field
    = f.collection_select :service_id, Service.all, :id, :title
  .fieldbody
    = f.label :body
    = f.text_area :body
  = f.fields_for :galleries do |p|
    .field
      = p.label :image
      %br/
      = p.file_field :image, :multiple => true, name: "galleries[image][]"
  .action_button_2
    = f.submit 'Save'

app/views/services/edit.html.haml
%h1 Editing service
= render 'form'
= link_to 'Show', @service
|
\#{link_to 'Back', services_path}

app/views/services/index.html.haml
#content.clearfix
  .column.split_3
    %h1 Services
    %div.service_index_table
      %ul
        - @services.each do |service|
          %li
            .service_item
              %h2= service.title.titleize
              .body_text
                = truncate(service.body.html_safe, :length => 400, :escape => false)
                = link_to " More", service

app/views/services/new.html.haml
.content
  %h1 New service
  = render 'form'
  = link_to 'Back', services_path

app/views/services/show.html.haml
.content.clearfix
  %ul.sub_menu
    - if @service.primary
      - @service.sub_services.each do |sub_service|
        %li= link_to sub_service.title, sub_service
    - else
      = link_to("< #{@service.parent.try(:title)}", service_path(@service.parent), class: "trail") unless @service.primary
- if @service.primary
  %ul.image_banner.split_10
    %li.split_33 
      = image_tag (@service.left_image)
    %li.split_33 
      = image_tag (@service.central_image)
    %li.split_33 
      = image_tag (@service.right_image)

- else
.content.clearfix
  .split_10
    -# IF STATEMENT FOR WHETHER 7 OR 9 PHOTOS ARE UPLOADED TO CHOOSE HOW MANY APPEAR ON LEFT
    %ul.left_pictures.column.split_1
      - if @service_attachments.count == 7
        - @service_attachments.first(3).each do |p|
          %li
            = image_tag p.picture_url(:left) if p.picture?
      - elsif @service_attachments.count == 8
        - @service_attachments.first(4).each do |p|
          %li
            = image_tag p.picture_url(:left) if p.picture?
      - else
        - @service_attachments.first(5).each do |p|
          %li
            = image_tag p.picture_url(:left) if p.picture?
    %ul.center_picture.column.split_6
      - @service_attachments.reverse.drop(3).first(1).each do |p|
        %li
          = image_tag p.picture_url(:service_center) if p.picture?
    -# CLASS FOR QUOTE DEPENDENT ON WHETHER ON PRIMMARY OR SECONDARY PAGE
    - if @service.primary 
      
    - elsif @service.quote?
      .quote.column.split_3
        = @service.quote
    - else
    %ul.right_pictures.column.split_2
      - @service_attachments.last(3).each do |p|
        %li
          = image_tag p.picture_url(:right) if p.picture?
  - if @service.primary
    .column.split_10
      .main_service_title.column.split_7
        %h1= @service.title.titleize
    .quote_primary.column.split_3
      = @service.quote
    .primary_body.column.split_7.body_text.space
      = @service.body.html_safe
  - else
    .service_body.column.split_6
      %h1= @service.title.titleize
      .body_text.space
        %p
          = @service.body.html_safe
  %ul.gallery.column.split_10
    - @galleries.each do |p|
      %li.column.split_33
        = image_tag p.image_url(:gallery_third) if p.image?
  - if @service.primary
    .primary_read_more.column.split_7
      %p Read More:
      %ul
        - @service.sub_services.each do |sub_service|
          %li= link_to sub_service.title + " / ", sub_service

app/views/static_pages/about.html.haml
.about_imgs.split_33
  = image_tag("about_4.jpg")
.about_imgs.split_33
  = image_tag("about_2.jpg")
.about_imgs.split_33
  = image_tag("about_3.jpg")
.about_content.content
  .column.split_7
    %h1 About Us
  .column.split_10
    .side_quote.column.split_3
      %h2 A Small Family run shop in Norfolk aiming to put the wow into your home and business.
    .column.split_7
      %h5 Wooden Art World came about from a holiday in Indonesia. A chance encounter meant we saw the art and furniture for the first time, and much like people who come to our shop - we were blown away. That is the funamental nature of our shop and company, we truly believe in the stunning nature of our products and continue to be amazed at the quality art and crafts of those small Indonesian Artists.
      %p We visit our artists and craftsman continually throughout the year to personally source the pieces that come into the UK. We also make requests for bespoke pieces, both directly from our customers and to bring some flavour to our store. It is this close relationship with those in Indonesia that helps drive our passion.<br><br>We have a strong belief and import all of our products directly from the artists and craftsman who make them. Because of this, we have full control over how the people making these stunning pieces get payed. We personally ensure that all those working to bring these things to you are paid well, that all things are produced ethically and responsibly.

app/views/static_pages/disclaimer.html.haml
.content
  %h1 Disclaimer

app/views/static_pages/index.html.haml
.image_scroll_bar  
  = image_tag('slide1.jpg')
  = image_tag('slide2.jpg')
  = image_tag('slide3.jpg')
  = image_tag('slide4.jpg')
.content
  .welcome_message.split_5
    %h3 Welcome. We are Wooden Art World. We sell Amazing and Unique hand-carved Art and Furniture. Take a look around.
  .service_grid_heading.split_8
    %h2 Our Works
  %ul.services_grid.clearfix
    - @primary_services.each do |service|
      %li.column.split_33
        %h3
          = service.title
        - service.service_attachments.reverse.drop(3).first(1).each do |p|
          = image_tag p.picture_url(:service_center) if p.picture?
        %p
          = service.body.truncate(375, escape: false, seperator:  ' ', omission: "#{link_to ' ... more', service, :class => "more_link"}").html_safe

app/views/static_pages/sitemap.html.haml
.content
  %h1 sitemap